spring.application.name=SpringBatchEstudio
spring.batch.jdbc.initialize-schema=embedded
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.schema-locations=classpath:org/springframework/batch/core/schema-h2.sql

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

batch.input.file=C:/Users/25191/Documents/Estudio/SpringBatchEstudio/data.csv
